AWSTemplateFormatVersion: 2010-09-09
Description: Example of an image builder component

Parameters:

  Version:
    Type: String
    Description: The Component and Recipe version
    Default: 0.0.1

Resources:

  ImageBuilderComponent:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: !Ref AWS::StackName
      Data: !Sub |
        name: AttiniCli - InlineData
        description: This is a image with basic AWS CI/CD programs and the Attini CLI
        schemaVersion: 1.0

        phases:
          - name: build
            steps:
              - name: build
                action: ExecuteBash
                inputs:
                  commands:
                    - echo "Install any software your application needs"

          - name: verify
            steps:
              - name: verify
                action: ExecuteBash
                inputs:
                  commands:
                    - echo "Verify your installations"
      Platform: Linux
      Version: !Ref Version




Outputs:

  Component:
    Value: !Ref ImageBuilderComponent
